signatures = ["3384c31fce4a7c008a8f7b2652bc48cc4321f1d2c877b18e30a4ed619af12f6b"]
source = "Katya Â® ðŸ‘½ System"
hasFsVeritySignatures = true

description = """
Apps is the client for the Katya Â® ðŸ‘½ System app repository. It's included in Katya Â® ðŸ‘½ System but can also be used on other Android 12+ operating systems.
"""
